apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminus-dev
  namespace: dev
spec:
  selector:
    matchLabels:
      run: terminus-dev
  replicas: 1
  template:
    metadata:
      labels:
        run: terminus-dev
    spec:
      containers:
        - name: terminustest
          #image: gcr.io/google-samples/node-hello:1.0
          image: ip-172-31-30-252.us-west-2.compute.internal/library/terminus
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "300m"
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: harbor-registry
